### PR TITLE
fix apparent CopyPaste error when assigning obd fault codes

### PR DESCRIPTION
**Pull request by mi-hol**
was merged in RE already

### CODE REVIEW

**Comment by mi-hol** [comment]
@mck1117 does reviewing this require more than 3 minutes?

**Comment by mck1117** [comment]
> @mck1117 does reviewing this require more than 3 minutes?

Yes, it does. I don't understand why the description "fix copy paste error" requires changing 1600 lines of a file. It adds `unused code:` to many lines, but I think that was already obvious as those lines were commented out. But it also touches some other file's OBD codes, so there's some other edit of a few lines "hidden" in the middle of those 1600 lines.

**Comment by mck1117** [comment]
looks like there are also numerous mis-edits

image

**Comment by mi-hol** [comment]
getting crap in was easy, removing it is quite difficult

**Pull request closed without merging**
