### PR TITLE
configure DFCO MAP threshold to vary based on RPM

### PR DESCRIPTION
**Pull request by alrijleh**
Addresses my idea proposed in https://github.com/FOME-Tech/fome-fw/issues/478

I did a brief test drive in my car to verify that it works.  Feel free to reject if this seems like it would contribute unnecessary bloat to the project.
Capture

### CODE REVIEW

**Comment by mck1117** [comment]
1. looks like a merge conflict in the TS template
2. I'd love to see a unit test for this new behavior!

**Comment by alrijleh** [comment]
On it.
Do you think it would make sense to also add a field to set hysterics for the MAP threshold?

**Comment by alrijleh** [comment]
Also, do you think the “ MAP ModE” drop-down selector is needed?  Fixed is the same as setting a flat table, but it allows the existing tune settings to work when updating to the new firmware for the first time.

**Comment by mck1117** [comment]
> Also, do you think the “ MAP Mode” drop-down selector is needed? Fixed is the same as setting a flat table, but it allows the existing tune settings to work when updating to the new firmware for the first time.

Yes - breaking back compat is sort of unacceptable, so the dropdown is required.

**Pull request merged**
