### PR TITLE
fix link to CHANGELOG.rusefi.md

### PR DESCRIPTION
**Pull request by mi-hol**

### CODE REVIEW

**Comment by mck1117** [comment]
why is it on a new line?

**Comment by mi-hol** [comment]
I don't believe that links are allowed in headings

**Comment by mck1117** [comment]
image

**Comment by mi-hol** [comment]
ok I didn't know that but would still prefer to keep it as a separate line due to better usability.

- Readers don't expect links in headers 
- an md file converted to other format may have addl. restrictions

What reasons do you see to have just a header and no further content?

**Pull request merged**
