### PR TITLE
replace deprecated Gha "set output"

### PR DESCRIPTION
**Pull request by mi-hol**
same change as in https://github.com/rusefi/rusefi/pull/5470/commits/1433777153ca7a5c56d5a09627c664945f22dee0

### CODE REVIEW

**Comment by mck1117** [comment]
does this resolve #200?

**Comment by mi-hol** [comment]
yes fixes #200

**Comment by mck1117** [comment]
excellent - remember to link related issues in the future 🙂

**Comment by mi-hol** [comment]
> remember to link related issues in the future

wanted to add "fixes" after successful build only

**Pull request merged**
